'use client';

import { useState, useMemo } from 'react';
import { calculateMovingCost, homeSizes, extras as extrasList, seasonalMultipliers } from '../data/moving-costs';
import { TruckIcon, BoxIcon, ChevronDownIcon, CalendarIcon, PackageIcon, DollarIcon, CopyIcon } from './icons';

const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const monthFullNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const homeSizeShortLabels = {
  studio: 'Studio',
  '1br': '1 BR',
  '2br': '2 BR',
  '3br': '3 BR',
  '4br': '4 BR',
  '5br': '5+ BR',
};

const moveTypeLabels = {
  full: 'Full Service',
  partial: 'Partial Service',
  diy: 'DIY',
};

const moveTypeIcons = {
  full: TruckIcon,
  partial: BoxIcon,
  diy: PackageIcon,
};

function getMonthColor(monthIndex) {
  const mult = seasonalMultipliers[monthIndex] ?? 1.0;
  if (mult <= 0.90) return 'green';
  if (mult >= 1.20) return 'orange';
  return 'blue';
}

function getMonthButtonClasses(monthIndex, isSelected) {
  if (isSelected) {
    return 'bg-gradient-to-r from-orange-500 to-orange-600 text-white shadow-lg';
  }
  const color = getMonthColor(monthIndex);
  if (color === 'green') return 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100 border border-emerald-200';
  if (color === 'orange') return 'bg-orange-50 text-orange-700 hover:bg-orange-100 border border-orange-200';
  return 'bg-blue-50 text-blue-700 hover:bg-blue-100 border border-blue-200';
}

function getSeasonalNote(multiplier) {
  if (multiplier <= 0.90) return { emoji: '\u{1F7E2}', text: 'Off-peak pricing', className: 'text-emerald-600' };
  if (multiplier <= 0.95) return { emoji: '\u{1F7E2}', text: 'Off-peak pricing', className: 'text-emerald-600' };
  if (multiplier <= 1.05) return { emoji: '\u{1F535}', text: 'Shoulder season', className: 'text-blue-600' };
  if (multiplier <= 1.10) return { emoji: '\u{1F7E1}', text: `Shoulder season (+${Math.round((multiplier - 1) * 100)}%)`, className: 'text-amber-600' };
  if (multiplier <= 1.20) return { emoji: '\u{1F534}', text: `Peak season (+${Math.round((multiplier - 1) * 100)}%)`, className: 'text-orange-600' };
  return { emoji: '\u{1F534}', text: `Peak season (+${Math.round((multiplier - 1) * 100)}%)`, className: 'text-red-600' };
}

function fmt(n) {
  return '$' + Math.round(n).toLocaleString();
}

const breakdownLabels = {
  labor: 'Labor',
  transportation: 'Transportation',
  packing: 'Packing Materials',
  insurance: 'Insurance',
  tips: 'Tips & Gratuity',
  extras: 'Extras & Add-ons',
};

export default function MovingCalculator({ originCity, destCity }) {
  const [homeSize, setHomeSize] = useState('2br');
  const [month, setMonth] = useState(new Date().getMonth());
  const [selectedExtras, setSelectedExtras] = useState([]);
  const [moveType, setMoveType] = useState('full');
  const [showBreakdown, setShowBreakdown] = useState(false);
  const [copied, setCopied] = useState(false);

  const result = useMemo(() => {
    return calculateMovingCost(originCity, destCity, {
      homeSize,
      month,
      extras: selectedExtras,
      moveType,
    });
  }, [originCity, destCity, homeSize, month, selectedExtras, moveType]);

  const seasonalNote = getSeasonalNote(result.seasonalMultiplier);

  function toggleExtra(id) {
    setSelectedExtras((prev) =>
      prev.includes(id) ? prev.filter((e) => e !== id) : [...prev, id]
    );
  }

  function copyEstimate() {
    const home = homeSizes.find((h) => h.id === homeSize);
    const breakdownLines = Object.entries(result.breakdown)
      .filter(([, val]) => val.mid > 0)
      .map(([key, val]) => `- ${breakdownLabels[key] || key}: ${fmt(val.mid)}`)
      .join('\n');

    const text = `Moving Estimate: ${originCity.name}, ${originCity.stateCode} \u2192 ${destCity.name}, ${destCity.stateCode}
Home Size: ${home?.label || homeSize}
Move Type: ${moveTypeLabels[moveType]}
Month: ${monthFullNames[month]}
Distance: ${result.distance.miles.toLocaleString()} miles

Estimated Cost: ${fmt(result.total.low)} - ${fmt(result.total.mid)} - ${fmt(result.total.high)}

Breakdown:
${breakdownLines}

Generated by MoveCostGuide.us`;

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const animKey = `${homeSize}-${month}-${moveType}-${selectedExtras.join(',')}-${originCity?.slug}-${destCity?.slug}`;

  return (
    <div className="bg-white rounded-2xl shadow-xl border border-gray-100 overflow-hidden">
      {/* Configuration Panel */}
      <div className="p-6 md:p-8 space-y-6 bg-gradient-to-b from-gray-50 to-white">
        {/* Home Size Selector */}
        <div>
          <label className="flex items-center gap-2 text-sm font-semibold text-gray-700 mb-3">
            <HomeIconSmall />
            Home Size
          </label>
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
            {homeSizes.map((size) => (
              <button
                key={size.id}
                onClick={() => setHomeSize(size.id)}
                className={`px-3 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 ${
                  homeSize === size.id
                    ? 'bg-gradient-to-r from-orange-500 to-orange-600 text-white shadow-lg shadow-orange-500/25 scale-105'
                    : 'bg-white text-gray-600 hover:bg-orange-50 border border-gray-200 hover:border-orange-300'
                }`}
              >
                {homeSizeShortLabels[size.id]}
              </button>
            ))}
          </div>
        </div>

        {/* Month Picker */}
        <div>
          <label className="flex items-center gap-2 text-sm font-semibold text-gray-700 mb-3">
            <CalendarIcon className="w-4 h-4" />
            Move Month
          </label>
          <div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-12 gap-1.5">
            {monthNames.map((name, idx) => (
              <button
                key={idx}
                onClick={() => setMonth(idx)}
                className={`px-2 py-2 rounded-lg text-xs font-medium transition-all duration-200 ${getMonthButtonClasses(idx, month === idx)}`}
              >
                {name}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-4 mt-2 text-[11px] text-gray-500">
            <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-emerald-400" /> Cheapest</span>
            <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-blue-400" /> Moderate</span>
            <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-orange-400" /> Expensive</span>
          </div>
        </div>

        {/* Extras */}
        <div>
          <label className="flex items-center gap-2 text-sm font-semibold text-gray-700 mb-3">
            <PackageIcon className="w-4 h-4" />
            Extras & Add-ons
          </label>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2">
            {extrasList.map((extra) => {
              const isSelected = selectedExtras.includes(extra.id);
              return (
                <label
                  key={extra.id}
                  className={`flex items-center gap-3 px-3 py-2.5 rounded-xl cursor-pointer transition-all duration-200 ${
                    isSelected
                      ? 'bg-gradient-to-r from-orange-500 to-orange-600 text-white shadow-md shadow-orange-500/20'
                      : 'bg-white border border-gray-200 text-gray-700 hover:border-orange-300 hover:bg-orange-50'
                  }`}
                >
                  <input
                    type="checkbox"
                    checked={isSelected}
                    onChange={() => toggleExtra(extra.id)}
                    className="sr-only"
                  />
                  <span className={`w-4 h-4 rounded flex items-center justify-center border-2 flex-shrink-0 transition-colors ${
                    isSelected ? 'bg-white/20 border-white/50' : 'border-gray-300'
                  }`}>
                    {isSelected && (
                      <svg className="w-3 h-3" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="2">
                        <polyline points="2 6 5 9 10 3" />
                      </svg>
                    )}
                  </span>
                  <span className="flex-1 text-sm font-medium">{extra.label}</span>
                  <span className={`text-xs flex-shrink-0 ${isSelected ? 'text-white/80' : 'text-gray-400'}`}>
                    {extra.cost != null ? `+${fmt(extra.cost)}` : `+${Math.round(extra.costMultiplier * 100)}%`}
                  </span>
                </label>
              );
            })}
          </div>
        </div>
      </div>

      {/* Move Type Tabs */}
      <div className="px-6 md:px-8 pt-2 pb-6">
        <div className="flex gap-2 p-1.5 bg-gray-100 rounded-2xl">
          {(['full', 'partial', 'diy']).map((type) => {
            const Icon = moveTypeIcons[type];
            const isActive = moveType === type;
            return (
              <button
                key={type}
                onClick={() => setMoveType(type)}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-xl text-sm font-semibold transition-all duration-200 ${
                  isActive
                    ? 'bg-gradient-to-r from-orange-500 to-orange-600 text-white shadow-lg shadow-orange-500/30'
                    : 'bg-white text-gray-600 hover:bg-orange-50'
                }`}
              >
                <Icon className="w-4 h-4" />
                <span className="hidden sm:inline">{moveTypeLabels[type]}</span>
                <span className="sm:hidden">{type === 'full' ? 'Full' : type === 'partial' ? 'Partial' : 'DIY'}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Results Area */}
      <div className="px-6 md:px-8 pb-6">
        <div
          key={animKey}
          className="bg-gradient-to-br from-orange-500 via-orange-600 to-amber-600 rounded-2xl p-6 md:p-8 text-white shadow-xl shadow-orange-500/20 animate-fade-in"
        >
          <div className="text-center mb-2">
            <p className="text-orange-100 text-sm font-medium mb-1">Estimated Moving Cost</p>
            <p className="text-orange-200 text-xs">
              {originCity.name}, {originCity.stateCode} → {destCity.name}, {destCity.stateCode}
              {' '}&middot;{' '}{result.distance.miles.toLocaleString()} miles
            </p>
          </div>

          <div className="flex items-end justify-center gap-4 md:gap-8 my-6">
            {/* Low */}
            <div className="text-center">
              <p className="text-orange-200 text-xs mb-1">Low</p>
              <p className="text-xl md:text-2xl font-bold text-orange-100">{fmt(result.total.low)}</p>
            </div>

            {/* Mid - prominent */}
            <div className="text-center">
              <p className="text-orange-100 text-xs mb-1 font-medium">Estimated</p>
              <p className="text-4xl md:text-5xl font-extrabold text-white tracking-tight">{fmt(result.total.mid)}</p>
            </div>

            {/* High */}
            <div className="text-center">
              <p className="text-orange-200 text-xs mb-1">High</p>
              <p className="text-xl md:text-2xl font-bold text-orange-100">{fmt(result.total.high)}</p>
            </div>
          </div>

          {/* Seasonal note */}
          <div className="text-center">
            <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-medium ${
              result.seasonalMultiplier <= 0.95
                ? 'bg-emerald-500/20 text-emerald-100'
                : result.seasonalMultiplier >= 1.15
                  ? 'bg-red-500/20 text-red-100'
                  : 'bg-blue-500/20 text-blue-100'
            }`}>
              {seasonalNote.emoji} {seasonalNote.text} &middot; {monthFullNames[month]}
            </span>
          </div>
        </div>
      </div>

      {/* Itemized Breakdown */}
      <div className="px-6 md:px-8 pb-6">
        <button
          onClick={() => setShowBreakdown((prev) => !prev)}
          className="flex items-center gap-2 w-full px-4 py-3 bg-gray-50 hover:bg-gray-100 rounded-xl transition-colors text-sm font-semibold text-gray-700"
        >
          <DollarIcon className="w-4 h-4 text-orange-500" />
          Itemized Breakdown
          <ChevronDownIcon
            className={`w-4 h-4 ml-auto transition-transform duration-300 ${showBreakdown ? 'rotate-180' : ''}`}
          />
        </button>

        {showBreakdown && (
          <div className="mt-3 overflow-hidden rounded-xl border border-gray-200">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider">
                  <th className="text-left px-4 py-3 font-semibold">Item</th>
                  <th className="text-right px-4 py-3 font-semibold">Low</th>
                  <th className="text-right px-4 py-3 font-semibold">Mid</th>
                  <th className="text-right px-4 py-3 font-semibold">High</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {Object.entries(result.breakdown)
                  .filter(([, val]) => val.mid > 0)
                  .map(([key, val]) => (
                    <tr key={key} className="hover:bg-gray-50 transition-colors">
                      <td className="px-4 py-3 text-gray-700">{breakdownLabels[key] || key}</td>
                      <td className="px-4 py-3 text-right text-gray-500">{fmt(val.low)}</td>
                      <td className="px-4 py-3 text-right text-gray-700 font-medium">{fmt(val.mid)}</td>
                      <td className="px-4 py-3 text-right text-gray-500">{fmt(val.high)}</td>
                    </tr>
                  ))}
                {result.seasonalMultiplier !== 1.0 && (
                  <tr className="hover:bg-gray-50 transition-colors">
                    <td className="px-4 py-3 text-gray-500 italic">
                      Seasonal adjustment ({result.seasonalMultiplier > 1 ? '+' : ''}{Math.round((result.seasonalMultiplier - 1) * 100)}%)
                    </td>
                    <td className="px-4 py-3 text-right text-gray-400 italic" colSpan={3}>
                      Applied to all line items
                    </td>
                  </tr>
                )}
              </tbody>
              <tfoot>
                <tr className="bg-gradient-to-r from-orange-50 to-amber-50 font-bold">
                  <td className="px-4 py-4 text-gray-900">Total Estimate</td>
                  <td className="px-4 py-4 text-right text-gray-600">{fmt(result.total.low)}</td>
                  <td className="px-4 py-4 text-right text-orange-600 text-base">{fmt(result.total.mid)}</td>
                  <td className="px-4 py-4 text-right text-gray-600">{fmt(result.total.high)}</td>
                </tr>
              </tfoot>
            </table>
          </div>
        )}
      </div>

      {/* Copy Estimate Button */}
      <div className="px-6 md:px-8 pb-8">
        <button
          onClick={copyEstimate}
          className="flex items-center justify-center gap-2 w-full px-4 py-3 bg-gray-900 hover:bg-gray-800 text-white rounded-xl transition-all duration-200 text-sm font-semibold shadow-lg hover:shadow-xl"
        >
          <CopyIcon className="w-4 h-4" />
          {copied ? 'Copied to Clipboard!' : 'Copy Estimate'}
        </button>
        {copied && (
          <p className="text-center text-xs text-emerald-600 mt-2 font-medium animate-fade-in">
            Estimate copied successfully
          </p>
        )}
      </div>

      <style jsx>{`
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(4px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 0.35s ease-out;
        }
      `}</style>
    </div>
  );
}

/* Small inline home icon to avoid importing HomeIcon just for a label */
function HomeIconSmall() {
  return (
    <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}
